### ISSUE TITLE
An easy way to fill nullable fields would be helpful.

### ISSUE THREAD

**Issue by DevJac** [vandersonmota/model_mommy#148]
I've previously use django_dynamic_fixture but recently switch to model_mommy.  I really miss the fill_nullable_fields option which would fill nullable fields as though they are required.

Even more helpful would be a way to specify which fields to fill.  Here's an example syntax.

``` python
model_mommy.mommy.make(MyModel, _fill=All())  # This fills all fields, even nullable fields.

model_mommy.mommy.make(MyModel, _fill=Exclude('boring_field'))  # This will fill all except boring_field, because who cares about boring_field?

model_mommy.mommy.make(MyModel, _fill=Include('my_nullable'))  # This will fill all required fields (which is already the default behavior), but will also fill the nullable field my_nullable.
```

The syntax is up for debate, but it illustrates the idea.  Fields which model_mommy doesn't know how to populate could be left null, or an error could be thrown.

**Comment by musemby** [comment]
@vandersonmota Hey was the API you suggested implemented?

**Comment by berinhard** [comment]
@musemby I *think* what you desired is implemented already. Take a look into the `_fill_optional` flag in [the docs](https://model-mommy.readthedocs.io/en/latest/how_mommy_behaves.html?highlight=optional#how-mommy-behaves).
