### ISSUE TITLE
Problem with AutoSlugField

### ISSUE THREAD

**Issue by csarcom** [vandersonmota/model_mommy#150]
https://pypi.python.org/pypi/django-autoslug

TypeError: class 'autoslug.fields.AutoSlugField' is not supported by mommy.

Any idea how can i solve it?

**Comment by jacobg** [comment]
It seems that for something like AutoSlugField, where it gets implicitly generated, then a custom field generator should be set to return None? Is that correct? e.g.,
```python
MOMMY_CUSTOM_FIELDS_GEN = {
    'django_extensions.db.fields.AutoSlugField': lambda: None
}
```

**Comment by stphivos** [comment]
Or if you are using django-autoslug repo directly:

```python
MOMMY_CUSTOM_FIELDS_GEN = {
    'autoslug.fields.AutoSlugField': lambda: None
}
```
