### ISSUE TITLE
Better handling subclasses for related fields

### ISSUE THREAD

**Issue by wolfe** [vandersonmota/model_mommy#164]
The most expedient way I found to create a new subclasses of ForeignKey was to monkey patch the Mommy class.  That's not best.  It does not appear easy to register new type mappings in settings for Foreign Keys as one can with other field types.

I'd be glad to submit a patch, but first I want some feedback on approach. My inclination would be to change all logic which dispatches to type_mapping to dispatch subclasses of  ForeignKey or OneToOneField to make/prepare as appropriate rather than merely the root class.  But once one goes down this path, there are all sorts of other options.  Should the entire dispatch logic pay attention to the class hierarchy (if you subclass BooleanField, by default does it dispatch to the same generator as BooleanField unless you override it?)

This isn't the only feasible approach.  There are two problems with overriding MOMMY_CUSTOM_FIELDS_GEN --- (1) circular import issue (cannot just import make in settings), and (2) logic which replaces make with prepare in the prepare method.  Another approach is to have special symbols which flag these.  E.g.,:
...
    CharField: generators.gen_string,
    TextField: generators.gen_text,
    SlugField: generators.gen_slug,

    ForeignKey: 'make_or_prepare',
    OneToOneField: 'make_or_prepare',
    ManyToManyField: __m2m_generator,
...
(or mommy.MAKE_OR_PREPARE which is not a function, but is a directive which substitutes in make or prepare as appropriate.)

**Comment by berinhard** [comment]
Closing this issue due inactivity.
