### ISSUE TITLE
Better support for generic foreign keys

### ISSUE THREAD

**Issue by macropin** [vandersonmota/model_mommy#186]
It would be great if support for a content_type whitelist, so you can specify which models are valid for the GFK relation and their associated foreign_key(recipe).

I also think the docs should be updated to include a example of GFK usage. eg:

`domain_binding = Recipe(DomainBinding, domain=foreign_key(domain), content_object=foreign_key(config)) `

**Comment by berinhard** [comment]
@macropin could you explain in which scenario you'd like to use this feature? And, also, what API do you propose to be used?

But I'm a :+1: for adding docs to the existing feature.

**Comment by vandersonmota** [comment]
closing due inactivity
