### ISSUE TITLE
Multiple RemovedInDjango19Warning

### ISSUE THREAD

**Issue by omeinusch** [vandersonmota/model_mommy#198]
I run my tests with `-Wall`. This is the result:

	~\\.env\lib\site-packages\model_mommy\mommy.py:5: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
	  from django.utils import importlib
	~\\.env\lib\site-packages\model_mommy\mommy.py:6: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and
	 admin submodules of django.contrib.contenttypes.
	  from django.contrib.contenttypes import generic
	~\\.env\lib\site-packages\model_mommy\mommy.py:9: RemovedInDjango19Warning: The utilities in django.db.models.loading are deprecated in favor of the new application loading system.
	  from django.db.models.loading import get_model
	Creating test database for alias 'default'...
	...........................................................~\\.env\lib\site-packages\django\db\models\sql\query.py:1142: RemovedInDjango19Warning: Passing callable arguments to queryset is deprecated.
	  value, lookups = self.prepare_lookup_value(value, lookups, can_reuse)
	...........

The tests itself are working. But it would be fine if the reasons for this warning will be removed as soon as possible.

**Comment by aericson** [comment]
What are the thoughts on this now that 1.8 is out, and deprecation warnings are loud, are we willing to drop support for 1.6 to address the deprecation warnings?

**Comment by aericson** [comment]
Created pull request at https://github.com/vandersonmota/model_mommy/pull/219

**Comment by epicserve** [comment]
I installed the PR #219 in my project and my projects tests pass now without the warnings. @aericson thanks for the work. Does anyone know when this might get merged in and made into a release?

**Comment by vandersonmota** [comment]
@epicserve already merged. I will make a release by the next month.
