### ISSUE TITLE
Contentype are not generated using the generator correctly

### ISSUE THREAD

**Issue by pombredanne** [vandersonmota/model_mommy#202]
See https://github.com/pombredanne/model_mommy/commit/c99520dd2555045a302ee53a363fc66570961c09
using issubclass fixes this. isinstance returns a ModelBase and never a ContentType

**Comment by berinhard** [comment]
Maybe we could add a test to ensure the failure and then apply the @pombredanne  commit to model mommy.

**Comment by pombreda** [comment]
its been a while :)

**Comment by berinhard** [comment]
@pombreda yeah, sorry about that. Yestarday we took part of the day off to update the issues and track them, so now we are going to solve one by one. Thanks for the patience.

**Comment by vandersonmota** [comment]
@tdruez added the test.
