### ISSUE TITLE
annoying.fields.AutoOneToOneField is not supported by mommy

### ISSUE THREAD

**Issue by cericoda** [vandersonmota/model_mommy#206]
I am wondering how to deal with creating related objects of the type [AutoOneToOneField](https://github.com/skorokithakis/django-annoying#autoonetoonefield)? 

I have worked around the problem previously by relying on the related object being created automatically,

It would be convenient to set it to be done automatically, but I can't see how to do it the way things are structured.

**Comment by vandersonmota** [comment]
Well, this is not a model_mommy issue, since it is a custom field. I've never used those, so i have no input about handling it. If anyone has, feel free to post it here.

**Comment by cericoda** [comment]
I would like to be able to specify that model_mommy handle it in the same way as a OneToOneField, this would work fine. But I can't see how to specify that. I tried it in settings.py - but since you shouldn't import many dependencies there I soon ran into trouble and couldn't get it to work. 

I feel that model_mommy would be enhanced if there was a way to specifiy that model_mommy will treat an AutoOneToOneField in the same way as a OneToOneField.
