### ISSUE TITLE
The `m2m_changed` signal is not fired

### ISSUE THREAD

**Issue by unaizalakain** [vandersonmota/model_mommy#210]
I'm listening for changes in some model through the  `post_save` signal. When creating an instance of that model, the `post_save` signal is fired before the m2m relations are saved. So I also listen to the `m2m_changed` signal that is supposed to be fired whenever any m2m relation changes in an instance, but when creating an instance with model_mommy no such signal is fired.

**Comment by vandersonmota** [comment]
hi @unaizalakain i saw your PR, but i made the following changes: 2ba228e

That said, if you don't specify a through model, mommy will use the ```add``` method, which fires the m2m_changed signal. Otherwise, m2m_changed will not be fired.

**Comment by unaizalakain** [comment]
@vandersonmota awesome, thank you!
