### ISSUE TITLE
Support for the BinaryField

### ISSUE THREAD

**Issue by Matt3o12** [vandersonmota/model_mommy#212]
Hey, it'd be cool if model-mommy would support django's BinaryField out of the box. The code I currently use to generate random binary data is:

    def gen_byte_string(s):
        return lambda: bytes(random.randint(0, 255) for x in range(s))

(Edit: I updated the algorithm).

**Comment by vandersonmota** [comment]
hey @Matt3o12 sorry about the delay. If you wish, you can send a PR with that code. ;-)

**Comment by berinhard** [comment]
Closing this issue since the commits were cherry-picked.
