### ISSUE TITLE
mommy.prepare seems to use the database

### ISSUE THREAD

**Issue by bh** [vandersonmota/model_mommy#226]
*1.2.4* does not work:

``` python
def test_language():
    marketplace = mommy.prepare("account.Marketplace", locale='yx_QZ')
    [...]

```
```
self = <django.db.backends.mysql.base.DatabaseWrapper object at 0x7f428868af28>

    def cursor(self):
        """
            Creates a cursor, opening a connection if necessary.
            """
        self.validate_thread_sharing()
        if self.queries_logged:
            cursor = self.make_debug_cursor(self._cursor())
        else:
>           cursor = utils.CursorWrapper(self._cursor(), self)
E           Failed: Database access not allowed, use the "django_db" mark to enable
```

*1.2.3* works fine.

**Comment by vandersonmota** [comment]
It changed in 1.2.4, because Django 1.8 does not accept unpersisted model instances as values for oneToOne and ForeignKey fields. However, i'm thinking about rolling back this behavior to previous Django versions. cc @berinhard

**Comment by vandersonmota** [comment]
fixed 08513f549bced36f6eddbe0bf95666b5de1d623d

If you're using or updating to Django 1.8 you might want to read: https://docs.djangoproject.com/en/1.8/releases/1.8/#assigning-unsaved-objects-to-relations-raises-an-error

**Comment by mdentremont** [comment]
Thanks @vandersonmota!

**Comment by inancsevinc** [comment]
@vandersonmota For django 1.8, is it possible to honor [allow_unsaved_instance_assignment](https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.ForeignKey.allow_unsaved_instance_assignment) setting? I mean in addition to this https://github.com/vandersonmota/model_mommy/commit/08513f549bced36f6eddbe0bf95666b5de1d623d commit, can we also add the check for `allow_unsaved_instance_assignment` and use prepare if it's true?

**Comment by vandersonmota** [comment]
@inancsevinc There is a way. I'm working on it. =)

**Comment by vandersonmota** [comment]
@inancsevinc https://github.com/vandersonmota/model_mommy/issues/227

**Comment by inancsevinc** [comment]
@vandersonmota great! thanks a lot.
