### ISSUE TITLE
Force prepare for Django 1.8

### ISSUE THREAD

**Issue by vandersonmota** [vandersonmota/model_mommy#227]
Since Django 1.8, a ForeignKey field will accept only a persisted instance to be assigned, unless you subclass the field and add ```allow_unsaved_instance_assignment```

it is not cool to make assumptions on custom models, but it's convenient to bypass this when need.

something like:
```python
mommy.prepare(dog, _force=True)
```
so that mommy will handle the whole drama. =)

**Comment by berinhard** [comment]
@vandersonmota i found that this is quite hard to understand and what this flag is going to do under the hood. Could you explain it better?

**Comment by berinhard** [comment]
@vandersonmota maybe we could also do not assume that this flag will be used for the next release and apply Django's 1.7 or lower versions behaviour to 1.8 too. So, if someone needs to have 1.8 behaviour, the person could open a PR or create an issue to enable this.

**Comment by vandersonmota** [comment]
fixed: 8b1c2e9
