### ISSUE TITLE
Can you push the latest master branch to PyPi?

### ISSUE THREAD

**Issue by aronysidoro** [vandersonmota/model_mommy#249]
Can you push the latest master branch to PyPi?

When you run: 

`pip install -U model_mommy` 

and then use model_mommy it gives Django 1.9 deprecation errors.

But when installing from git as: 

`pip install git+https://github.com/vandersonmota/model_mommy.git` 

there are no deprecation errors.

**Comment by vandersonmota** [comment]
https://pypi.python.org/pypi/model_mommy/1.2.5

;-)

**Comment by aronysidoro** [comment]
Great!  And thank you for this awesome library.  It has made testing in Django so much easier!
