### ISSUE TITLE
field.related deprecation warning with Django 1.8.

### ISSUE THREAD

**Issue by pmdarrow** [vandersonmota/model_mommy#255]
https://github.com/vandersonmota/model_mommy/blob/master/model_mommy/mommy.py#L73 raises the following deprecation warning in Django 1.8:

```django.utils.deprecation.RemovedInDjango110Warning: Usage of field.related has been deprecated. Use field.rel instead.```

**Comment by vandersonmota** [comment]
Thank you @pmdarrow 
We'll investigate

**Comment by vandersonmota** [comment]
@pmdarrow fixed: caa4e09
