### ISSUE TITLE
Issue with 8b1c2e9c020559024c1aa7192b0dfcdae83426cb

### ISSUE THREAD

**Issue by bh** [vandersonmota/model_mommy#257]
Hi,

I'm on Python 3.4.3, so mock is builtin (unittest.mock), you know. 

Example
``` python
from unittest import mock

@mock.patch.object(Api, '_make_request')
def test_make_price_info_request_successful(mock_make_request, pricing_api,
                                            pricing_response_example_as_json):
    mock_make_request.return_value = pricing_response_example_as_json
    [...]
```
```
Result:
        fixture 'mock_make_request' not found
        available fixtures: [...] transactional_db,  pytestbdd_given_trace, cov
        use 'py.test --fixtures [testpath]' for help on them.

```
So all tests with a mock decorator will fail.

I can fix this issue when I use

``` python
from mock import mock
```
instead of

``` python
from unittest import mock
```
I think, 8b1c2e9c020559024c1aa7192b0dfcdae83426cb needs an improvement.

Today or tomorrow I will create a pull request for this issue. OK?

Benjamin

**Comment by vandersonmota** [comment]
Hi @bh 
I've reverted this patching. see here: https://github.com/vandersonmota/model_mommy/commit/ace331a9b7398dd5fb2cd54843fc4c0cc32d1ade

I'll create a new version soon, meanwhile you can point to this commit.

[]'s

**Comment by vandersonmota** [comment]
pushed to pypi. 1.2.5.1

[]'s

**Comment by bh** [comment]
1.2.5.1 does not fix this issue. Why does model_mommy still require mock?

https://github.com/vandersonmota/model_mommy/blob/caa4e093146c36310183a1f92684c97e28bfbb47/model_mommy/mommy.py#L60

https://github.com/vandersonmota/model_mommy/search?utf8=%E2%9C%93&q=mock

Without mock as requirement, it is possible, that I can try to revert my workaround.

**Comment by bh** [comment]
?

**Comment by vandersonmota** [comment]
Sorry, i forgot to remove mock as project dependency. I'll review and solve the remaining problems this weekend.
