### ISSUE TITLE
Django 1.9: CharField subclasses with choices no longer supported

### ISSUE THREAD

**Issue by pmdarrow** [vandersonmota/model_mommy#261]
Using Django 1.9 and https://github.com/vandersonmota/model_mommy/pull/260, and the following field:

```python
class CurrencyField(models.CharField):
    """
    Stores an ISO 4217 currency code
    """
    choices = CURRENCY_CHOICES
```

I get:
```python
TypeError: <class 'core.fields.CurrencyField'> is not supported by mommy
```

With Django 1.8 and model_mommy, this was supported fine with no extra configuration.

**Comment by vandersonmota** [comment]
The fact which was strange is this field being supported by model_mommy without configuration. (Is it a custom field, right?)

**Comment by pmdarrow** [comment]
It is a custom field, but it appears that model_mommy doesn't care (see https://github.com/vandersonmota/model_mommy/blob/ace331a9b7398dd5fb2cd54843fc4c0cc32d1ade/model_mommy/mommy.py#L435) and just checks for the presence of a `choices` attribute. So it's not surprising to me that it worked before. `field.choices` evaluates to `[]` in that `generate_value` function with Django 1.9 for some reason.

**Comment by berinhard** [comment]
Hi @pmdarrow, thanks for creating this issue, but I'm closing it because this usage of choices for a custom field is wrong.

In Django, the `choices` attribute should be an `**instance** one, not a **class** one, as in this current `CurrencyField` class. Here is the correct implementation that still working with model mommy: 

```python
class CurrencyField(models.CharField):

    def __init__(self, *args, **kwargs):
        kwargs['choices'] = CURRENCY_CHOICES
        super(CurrencyField, self).__init__(*args, **kwargs)
```
