### ISSUE TITLE
Django 1.9 support

### ISSUE THREAD

**Issue by petkostas** [vandersonmota/model_mommy#262]
The related model object descriptor classes in django.db.models.fields.related (private API) are moved from the related module to related_descriptors and renamed:

ReverseSingleRelatedObjectDescriptor is ForwardManyToOneDescriptor
SingleRelatedObjectDescriptor is ReverseOneToOneDescriptor
ForeignRelatedObjectsDescriptor is ReverseManyToOneDescriptor
ManyRelatedObjectsDescriptor is ManyToManyDescriptor

This prevents of mommy working properly with the new version:
```
from model_mommy import mommy
../virtualenv/3.4/lib/python3.4/site-packages/model_mommy/mommy.py:24: in <module>
    from django.db.models.fields.related import ForeignRelatedObjectsDescriptor
E   ImportError: cannot import name 'ForeignRelatedObjectsDescriptor'
```

**Comment by vandersonmota** [comment]
thanks @petkostas 
we'll fix it soon

**Comment by vandersonmota** [comment]
fixed. On pypi
