### ISSUE TITLE
Remove code duplication by using tox on Travis

### ISSUE THREAD

**Issue by jonashaag** [vandersonmota/model_mommy#264]
Look how it's done here: https://github.com/AndrewIngram/django-extra-views/blob/master/.travis.yml, https://github.com/AndrewIngram/django-extra-views/blob/master/tox.ini

- In `.travis.yml`, only include aliases like `DJANGO=django18` etc. and call tox with `tox -e py${TRAVIS_PYTHON_VERSION//[.]/}-$DJANGO`
- In `tox.ini`, map `django18` to `Django>=1.8,<1.9`

**Comment by vandersonmota** [comment]
@jonashaag thank you for the tip. It's done: c3dcbbbeb9b2c845756a25af56f3de14006a4164

**Comment by jonashaag** [comment]
Cool! Another tip, you don't really need sudo and can still `apt-get install` packages. This makes it possible for your builds to run using Travis' container infrastructure, which means lower build latencies for you. See example here https://github.com/jonashaag/klaus/blob/master/.travis.yml
