### ISSUE TITLE
It's not possible to register a custom field generator in a distributable way

### ISSUE THREAD

**Issue by Kazade** [vandersonmota/model_mommy#269]
I have a reusable Django app with a custom field. What I'd like to do is something like:

```
class MyField(models.Field):
    pass

MyField._mommy_generator = some_generator
```

So that users of the library aren't required to manipulate their settings to make their tests work when they use this custom field.

**Comment by berinhard** [comment]
@Kazade when @vandersonmota started model_mommy and as I was helping, we were always very concerned about not trespassing the tests frontiers and sending testing code do `models.py` or others django app component. The API you are proposing violates that constraint so we don't think it is a good way to solve this problem.

Could you think about or propose another API that solves this kind of problem?

**Comment by vandersonmota** [comment]
closed in favor of https://github.com/vandersonmota/model_mommy/issues/275
