### ISSUE TITLE
Register/Unregister field generators without using settings.py

### ISSUE THREAD

**Issue by vandersonmota** [vandersonmota/model_mommy#275]
The main purpose is to configure field's value generator function with a API provided by model_mommy, like this:

``` python
# mymodule.py
from model_mommy import generators
def gen_func():
    return 'value'
generators.set('test.generic.fields.CustomField', gen_func)

```

instead of the current option, with settings: http://model-mommy.readthedocs.org/en/latest/how_mommy_behaves.html#custom-fields

**Comment by dirtycoder** [comment]
Hey guys, I'll try to take a look at it, ok?

**Comment by berinhard** [comment]
Sure @dirtycoder

**Comment by dirtycoder** [comment]
Quick question, what is the deprecation policy of model_mommy?
