### ISSUE TITLE
Reverse one-to-one relationships are not created

### ISSUE THREAD

**Issue by wolever** [vandersonmota/model_mommy#280]
See failing test here: https://github.com/wolever/model_mommy/commit/76b1e8e8a8adf2ad243393434c67b9f7cc568fc8

This test is failing against the current master (c7aa8d923f842d6961d8f56a6f34635c68352e87)

**Comment by aronysidoro** [comment]
@wolever,

I had submitted a similar issue before. Not sure if this applies to what you're saying?

https://github.com/vandersonmota/model_mommy/issues/272

**Comment by vandersonmota** [comment]
@wolever it think it's related with what @aronysidoro reported.
