### ISSUE TITLE
JSONField support

### ISSUE THREAD

**Issue by aronysidoro** [vandersonmota/model_mommy#281]
Are there any plans for JSONField support with Postgres' JSONb field?

Is this something that could be added if I submit a pull request?

**Comment by vandersonmota** [comment]
@aronysidoro sure thing. You may use the `development` branch as basis, since tox runs the tests on PgSQL

**Comment by aronysidoro** [comment]
@vandersonmota cool. I'm going to do that then. Thanks!

**Comment by vandersonmota** [comment]
@aronysidoro i just didi it. 05a5590
