### ISSUE TITLE
Integrity Error being thrown with unique_together fields & m2m relationships

### ISSUE THREAD

**Issue by nanorepublica** [vandersonmota/model_mommy#286]
Hi there,

We have just started getting this error from the 1.3.0 release and I nailed it down to the switch from `.prepare` to `.make` in the `related` class.

Currently calling mommy like so:

```
bls = mommy.make_recipe('founders.leaders.leader_with_positions', profile_company=None, _quantity=3, make_m2m=True,
                                _fill_optional=['firstName', 'linkedin', 'publicProfileUrl', 'formattedName'])
```

The unique_together is on the following 3 fields: 'firstName', 'linkedin', 'publicProfileUrl'.

By the looks of it mommy never has a chance to fill in the relevant optional fields as it drops into saving m2m fields which at some point then tries to save the first model before filling its optional fields. This feels like a bug, but it might also be a scenario where we need to use the new custom mommy feature?

Let me know if you need any more info.

**Comment by vandersonmota** [comment]
If you need the optional fields to be filled you need to pass `_fill_optional=True` 
see https://model-mommy.readthedocs.io/en/latest/how_mommy_behaves.html?highlight=optional

**Comment by vandersonmota** [comment]
closing due inactivity
