### ISSUE TITLE
Clean or use temp files for FileFields

### ISSUE THREAD

**Issue by berinhard** [vandersonmota/model_mommy#303]
Currently, model mommy creates dummy images or text filles for `models.ImageField` or `models.FileField` and, after being created, those files aren't removed. This leaves the development environment with a lot of dummy files as you can see in this screen shot. A good idea is to change this behaviour to use temporary files or to remove created files when tests finishes (I think temp files are better because are more transparent to the user).

![files](https://cloud.githubusercontent.com/assets/238223/21718430/a29b7140-d3fe-11e6-9bd1-89ada0c8dd1c.png)

**Comment by robertfw** [comment]
It would also be nice to have a simple flag to turn this off - didn't notice this feature until it had created >100k files in my source tree. Was wondering why everything had mysteriously gotten so slow :p
