### ISSUE TITLE
`_save_related` parameter breaks compatibility

### ISSUE THREAD

**Issue by champ** [vandersonmota/model_mommy#307]
Hi,

Nowadays, people more or less expect that the versioning is semantic (http://semver.org), where major versions introduce incompatible changes, minor versions add backwards-compatible functionality and patch versions fixes bugs in a backwards-compatible manner. 

The behavior of new `_save_related` parameter introduced in 1.3.1 breaks backwards compatibility in [version 1.3.2](https://github.com/vandersonmota/model_mommy/blob/1.3.2/model_mommy/mommy.py#L61) even though it is a patch version. Two good options in those cases would have been:

* Make the behavior of the parameter backwards-compatible (default value set to `True`) and tag the version as a minor release (i.e. 1.4.0),  since it is adding functionality, not fixing a bug

or
 
* Introduce the parameter with non-backwards-compatible behavior in major version (i.e. 2.0.0) and flag the new parameter as breaking backwards compatibility

Since the version already has been released, the best option would probably be to change the default value to `True` making the behavior backwards-compatible, and change the default value to `False` in a 2.0.0 version.

**Comment by vandersonmota** [comment]
Sorry about the late response @champ 

> Make the behavior of the parameter backwards-compatible (default value set to True) and tag the version as a minor release (i.e. 1.4.0), since it is adding functionality, not fixing a bug

Seems good enough. Thanks!

**Comment by berinhard** [comment]
I'm closing this task because there were other 2 releases after the `1.4.0` one (`1.5.0` and `1.5.1`). So, changing this would make more complicated. Sorry about the delay on addressing this and also sorry about my poor decision @champ.
