### ISSUE TITLE
Error when using the JSONField()

### ISSUE THREAD

**Issue by elcolie** [vandersonmota/model_mommy#314]
```python
class OrderItem(models.Model):
    booking = models.ForeignKey(FactoryBooking, related_name='order_items')
    order_item_data = JSONField(blank=True, verbose_name="order item data"))

```

`mommy.make(OrderItem)`
```bash
IntegrityError: null value in column "order_item_data" violates not-null constraint
DETAIL:  Failing row contains (9, null, 0, 1.00, 0, null, 369).
```

I have the existing data and then try `mommy.make`<br>
Am I miss something `Django 1.11`
Python `3.6.0`

**Comment by vandersonmota** [comment]
thanks for the report @elcolie

**Comment by vandersonmota** [comment]
Ok, digging in a bit further i found this is Django's default behaviour.

JSONField does not behaves like Char and Text fields, where they set a blank string `''` by the time they are instantiated. Some good ways to handle that idiosyncrasy:
`mommy.make(OrderItem, _fill_optional=['order_item_data'])`
`mommy.make(OrderItem, _fill_optional=True)` -> this one would fill all blanks and nulls
`mommy.make(OrderItem, order_item_data='')`

If that becomes too cumbersome, you can always rely on recipes: https://model-mommy.readthedocs.io/en/latest/recipes.html

**Comment by elcolie** [comment]
Thank you for your response. Very informative. If I have any question I will get back to you again.
