### ISSUE TITLE
_fill_optional for OneToOneFields?

### ISSUE THREAD

**Issue by ChillarAnand** [vandersonmota/model_mommy#323]
Currently `_fill_optional` fills only fields for the current model it is creating leaving empty fields in related models. Is it possible to fill those values also without leaving them empty?

**Comment by vandersonmota** [comment]
Hmm.. i see. Sorry about the delay btw.

Although i can see the value in doing it, you're the first person raising the concern. I'm willing to add this if more people thinks this is needed. cc @berinhard
