### ISSUE TITLE
field with incorrect value if it has validator

### ISSUE THREAD

**Issue by joaojunior** [vandersonmota/model_mommy#334]
If I have a validator in the model field, sometimes the value generated is incorrect. 
As instance, If I have the field bellow in the model:
```
positive_float = models.FloatField(validators=[validators.MinValueValidator(0.001)])
```
The negative value is generate for this field.

**Comment by vandersonmota** [comment]
You should use `Recipes` https://model-mommy.readthedocs.io/en/latest/recipes.html
