### ISSUE TITLE
Release new version supporting Django 2.0

### ISSUE THREAD

**Issue by Eagllus** [vandersonmota/model_mommy#343]
Hi quick question,

With the release of Django 2.0 the `remote_field.to` function has been deprecated.
I noticed in [mommy.py#L390](https://github.com/vandersonmota/model_mommy/blob/development/model_mommy/mommy.py#L390) that you already fixed the problem.

So my request is can you create a new version?

**Comment by mpasternak** [comment]
+1

**Comment by fernand0silva** [comment]
+1

**Comment by berinhard** [comment]
Hey guys, I'm planning this relase as soon as possible, but I just want to configure tox to run the tests with Django 2.0 and also look deeper to check if #344 is an issue indeed.

I've created #346 task to address the tox thing and it would be amazing if I could get some help on it.

Thanks!

**Comment by Eagllus** [comment]
I created a pull request to have the tests run with Django 2.0 https://github.com/vandersonmota/model_mommy/pull/347

**Comment by berinhard** [comment]
I've already merged @Eagllus PR and we're good to go for a new release. I'm a little bit busy today, bur I really want to make it this weekend. I'll let you know as soon as I release it.

**Comment by vbabiy** [comment]
Been using master on Django 2.0, works great no issues so far.

**Comment by berinhard** [comment]
Xmas gift for you: https://pypi.python.org/pypi/model_mommy/1.5.0 =)
