### ISSUE TITLE
Django 2.0: set() got an unexpected keyword argument 'bulk'

### ISSUE THREAD

**Issue by karyon** [vandersonmota/model_mommy#344]
[this line](https://github.com/vandersonmota/model_mommy/blob/development/model_mommy/mommy.py#L344) in model mommy throws this error for me with django 2.0: 

`TypeError: set() got an unexpected keyword argument 'bulk'"`

called from my project [here](https://github.com/fsr-itse/EvaP/blob/8532aeb90cc9fc9225373b28b4ce39cb9cadfc8b/evap/evaluation/tests/test_models.py#L395)

fwiw, for me it only happens on the UserProfile, which has a [custom manager](https://github.com/fsr-itse/EvaP/blob/8532aeb90cc9fc9225373b28b4ce39cb9cadfc8b/evap/evaluation/models.py#L808)

django has two such set methods, [here](https://github.com/django/django/blob/8838d4dd498c8f66ea4237fe8a79a5f77d6f95c9/django/db/models/fields/related_descriptors.py#L656) and [here](https://github.com/django/django/blob/8838d4dd498c8f66ea4237fe8a79a5f77d6f95c9/django/db/models/fields/related_descriptors.py#L917), only the first of which has the parameter bulk. 

breaking commit in django is [here](https://github.com/django/django/commit/8838d4dd498c8f66ea4237fe8a79a5f77d6f95c9)

**Comment by berinhard** [comment]
@karyon, currently there's an open PR to run the tests with Django 2.0 (here #347). Once we have the tests running, we'll be able to debug this error properly.

**Comment by karyon** [comment]
hey, do you still have this on your radar? is there any chance you will fix this any time soon? i could try to fix it myself, but don't know when i'll find the time, and a little guidance would be nice as well...

**Comment by berinhard** [comment]
@karyon we've added django 2.0 support already. Now I think is safe for you to work on this if you can. You can start by writing a test reproducing the error you've described and them implement the code to make it pass. Probably you can add you test near to [these ones](https://github.com/vandersonmota/model_mommy/blob/development/test/generic/tests/test_mommy.py#L214).
