### ISSUE TITLE
Option of "Integer generator" generate only positive numbers

### ISSUE THREAD

**Issue by aipi** [vandersonmota/model_mommy#351]
I am creating a test with mommy where a apply it to generate numbers of an attribute and after that, to do a request.

_The piece of the test:_
```python
channel = mommy.make(Channel)

request = self.client.get(
            reverse('core:add_number_to_channel',
                    args=[self.channel.asn.number,
                          self.channel.uuid]))
```

_Message raised:_

`E   django.urls.exceptions.NoReverseMatch: Reverse for 'add_asn_to_channel' with arguments '(-1422, UUID('fdb36645-937c-4c4c-b78d-1ca981dc42a5'))' and keyword arguments '{}' not found. 1 pattern(s) tried: ['core/form/add-asn-to-channel/(?P<asn>[\\d]+)/(?P<channel>[0-9a-f]{8}-[0-9a-f]{4}-[4][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12})/$']`

`/usr/local/lib/python3.5/site-packages/django/urls/resolvers.py:392: NoReverseMatch`

I do not instance `ASN` and pass to `Channel`, because of model-mommy already treat it for me, instancing this dependency and generating random integers (**-1422** in this case of the raised message), once that `ASN` is a foreign key of `Channel`. It could work normally, however `ASN.number` has a validator to accept only positive numbers. It turns my test unpredictable to know if the number is positive or negative. Does exist a way for the treat it without the necessity of using a third party tool (I swear that I still did not think how would do it) or without instance `ASN` with a fixed positive number value? Does mommy take care of this kind of cases?

**Comment by berinhard** [comment]
@aipi by default model mommy does not take care of this kind of cases. But there are ways you can solve this:

- Using [model mommy's recipes](https://model-mommy.readthedocs.io/en/latest/recipes.html);
- [Customizing your field type](https://model-mommy.readthedocs.io/en/latest/how_mommy_behaves.html#custom-fields) to use a generator function as we do [in PositiveIntegerField generator](https://github.com/vandersonmota/model_mommy/blob/development/model_mommy/generators.py#L64);
