### ISSUE TITLE
NullBooleanField should be treated as BooleanField(null=True, blank=True)

### ISSUE THREAD

**Issue by satyanash** [vandersonmota/model_mommy#356]
Currently when using `_fill_optional=True`, Model Mommy will randomly choose between `(None, False, True)` for a `NullBooleanField`.
This feature was added in #305, but I think if `_fill_optional=True` is specified, it should treat a `NullBooleanField` the same as a `BooleanField(null=True, blank=True)` as Django recommends using `NullBooleanField` where there is a use case for the empty state in a boolean field.

Model Mommy treats `None` here as a valid non-empty value even though it still means that the field is empty. This confuses any tests that assume that `_fill_optional=True` will guarantee no `None` values.

**Comment by Nuurek** [comment]
Somehow related: https://docs.djangoproject.com/en/dev/releases/2.1/

> BooleanField can now be null=True. This is encouraged instead of NullBooleanField, which will likely be deprecated in the future.

**Comment by berinhard** [comment]
I'm a :+1: for this change in model mommy.
