### ISSUE TITLE
mommy does not support `CIEmailField`

### ISSUE THREAD

**Issue by tucosaurus** [vandersonmota/model_mommy#357]
Trying to `mommy.make` a custom user model with the email field renders the following error:

```
TypeError: <class 'django.contrib.postgres.fields.citext.CIEmailField'> is not supported by mommy.
```

**Comment by tucosaurus** [comment]
Maybe we can look into how [django-dynamic-fixture](https://github.com/paulocheque/django-dynamic-fixture/blob/master/django_dynamic_fixture/fixture_algorithms/default_fixture.py#L87) does it.

**Comment by berinhard** [comment]
Thanks @tucosaurus! I'm going to take a look and maybe add it to the next release.

**Comment by berinhard** [comment]
Django docs ref.: https://docs.djangoproject.com/en/2.0/ref/contrib/postgres/fields/#citext-fields
