### ISSUE TITLE
Stick to Django support's roadmap

### ISSUE THREAD

**Issue by berinhard** [vandersonmota/model_mommy#365]
As listed [here](https://www.djangoproject.com/weblog/2015/jun/25/roadmap/), Django's versions lower than 1.11 aren't supported anymore. 

Since there are **a lot** of versioning conditions in model mommy's code, I really think it would be good to also drop django's 1.8, 1.9 and 1.10 version support and to clean up the code a little bit.

**Comment by anapaulagomes** [comment]
I'm on it.
